#!/bin/sh

echo "🧹 PHP-CS-Fixer через Docker контейнер lara_bridge_app..."

# fixed in container
docker compose exec -T lara_bridge_app vendor/bin/php-cs-fixer fix --config=/var/www/.php-cs-fixer.dist.php --verbose

# add fixed to commit
git add .
