#!/bin/sh

echo "Running PHP CS Fixer to automatically fix code style issues..."

# Запускаем исправление внутри контейнера Docker
# Обратите внимание на 'app', имя вашего сервиса
docker-compose exec app ./vendor/bin/php-cs-fixer fix

# Добавляем автоматически исправленные файлы в коммит
git add .

echo "Code style applied and changes staged. Committing..."

exit 0
