#!/bin/sh

echo "🧹 Запуск PHP-CS-Fixer в Docker..."

docker compose exec -T php php-cs-fixer fix --config=.php-cs-fixer.dist.php --allow-risky=yes

if [ $? -ne 0 ]; then
    echo "❌ PHP-CS-Fixer нашёл ошибки. Закоммить исправления и повтори push."
    exit 1
fi

echo "✅ Всё ок! Продолжаю push."
