name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Устанавливаем Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt update
        sudo apt install -y docker-compose

    # Собираем контейнеры
    - name: Build Docker Compose
      run: docker-compose -f docker-compose.yml build

    # Запускаем контейнеры
    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d
      run: docker-compose run --rm app composer install --no-progress --no-interaction

    # Запускаем тесты
    - name: Run tests
      run: docker-compose run --rm app php artisan test

    # Проверяем код линтером (если есть)
    - name: Code style check
      run: docker-compose run --rm app vendor/bin/php-cs-fixer fix --dry-run --diff
