name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Проверяем Docker
    - name: Check Docker version
      run: docker --version

    - name: Check Docker Compose version
      run: docker compose version

    # Собираем и запускаем контейнеры для CI
    - name: Build and Run CI Containers
      run: |
        docker compose -f docker-compose.ci.yml build
        docker compose -f docker-compose.ci.yml up -d

    # Устанавливаем зависимости Laravel
    - name: Install PHP dependencies
      run: docker compose -f docker-compose.ci.yml run --rm app composer install --no-progress --no-interaction

    # Запускаем тесты
    - name: Run tests
      run: docker compose -f docker-compose.ci.yml run --rm app php artisan test

    # Проверяем код php-cs-fixer
    - name: Code style check
      run: docker compose -f docker-compose.ci.yml run --rm app vendor/bin/php-cs-fixer fix --dry-run --diff
